services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  back:
    build:
      context: ./back
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
    command: ["npm", "run", "start:dev"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  front:
    build:
      context: ./front
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - ./front:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    depends_on:
      - back
